#!/bin/bash
# ============================================================================
# File name   : post-commit
# Description : git post-commit hook to save a version number on every commit
# Author(s)   : Michael Hucka <mhucka@caltech.edu>
# Organization: California Institute of Technology
# Date created: 2020-05-04
#
# This hook and the companion pre-commit hook need to be installed in your
# local copy of the repository.  One way to do that is to configure git to
# look for hooks in a local directory:
#
#   git config core.hooksPath .githooks
#
# ============================================================================

root=$(git rev-parse --show-toplevel)
versionfile=$root/site/data/site.toml

if [[ -e $versionfile.needcommit ]]; then
    rm -f $versionfile.needcommit
    git commit --amend -C HEAD --no-verify --allow-empty-message $versionfile
fi
