//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libsbml {

public class ModelCreatorList : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ModelCreatorList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ModelCreatorList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ModelCreatorList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsbmlPINVOKE.delete_ModelCreatorList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ModelCreatorList() : this(libsbmlPINVOKE.new_ModelCreatorList(), true) {
  }

  public void add(ModelCreator item) {
    libsbmlPINVOKE.ModelCreatorList_add(swigCPtr, ModelCreator.getCPtr(item));
  }

  public ModelCreator get(uint n) {
    global::System.IntPtr cPtr = libsbmlPINVOKE.ModelCreatorList_get(swigCPtr, n);
    ModelCreator ret = (cPtr == global::System.IntPtr.Zero) ? null : new ModelCreator(cPtr, false);
    return ret;
  }

  public void prepend(ModelCreator item) {
    libsbmlPINVOKE.ModelCreatorList_prepend(swigCPtr, ModelCreator.getCPtr(item));
  }

  public ModelCreator remove(uint n) {
    global::System.IntPtr cPtr = libsbmlPINVOKE.ModelCreatorList_remove(swigCPtr, n);
    ModelCreator ret = (cPtr == global::System.IntPtr.Zero) ? null : new ModelCreator(cPtr, false);
    return ret;
  }

  public uint getSize() {
    uint ret = libsbmlPINVOKE.ModelCreatorList_getSize(swigCPtr);
    return ret;
  }

}

}
