#!/bin/bash
# ============================================================================
# File name   : update-spreadsheet-timestamp
# Description : Script to check the SBML L3 package spreadsheet for changes
# Author(s)   : Michael Hucka <mhucka@caltech.edu>
# Organization: California Institute of Technology
# Date created: 2020-05-15
#
# Hugo is a static site generator, which means all the pages in our website
# are actually static HTML pages -- no data lookup is performed at run time.
# Hugo does have the ability to detect changes in the source files used to
# produce the site (when running in file-watch mode), but that doesn't extend
# to documents outside of the site itself.  In particular, the lack of
# ability to watch a remote URL or to run code means that if our site is
# built using data in a remote location (such as our Google spreadshet of
# SBML L3 packages), we need some other system to watch for changes and
# inform Hugo to rebuild the site.
#
# The approach used currently is to run an external (to Hugo) process that
# periodically checks the Google spreadsheet for updates, and if any changes
# are found, to trigger a site rebuild by Hugo.  The triggering mechanism
# is simple: just touch a file in the site source directory.  That's enough
# to make Hugo think something has changed, and rebuild the site (again,
# assuming it's watching in in file-watch mode)
#
# This script is intended to be run from cron or a similar system daemon
# control system (e.g., Jenkins).  Here's an example of a cron entry:
#
#   */10 * * * * /home/hugo/sbml/admin/update-spreadsheet-timestamp >> /var/log/hugo/spreadsheet-updates.log 2>&1
#
# Assumptions for purposes of the SBML.org site repository:
# - this script is located in the local repository copy
# - permissions on this script and other things are set up properly
# -----------------------------------------------------------------------------

# Because this is run from cron, we may need to include /usr/local/bin/.
PATH=/usr/local/bin:/opt/local/bin:/bin:/usr/bin

# Find out the directory where this file is located.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

# Read the server configuration file.
source $DIR/server.cfg

# Read the URL for the Google spreadsheet timestamp value.
DATA_FILE="$SITE_ROOT/data/SBML.toml"
TIMESTAMP_URL=$(awk -F " = " '/package_spreadsheet_timestamp/ {print $2}' $DATA_FILE | tr -d '"')

# Where do we store the timestamp from the SBML L3 package spreadsheet?
# IMPORTANT: this has to be a file in the /site/content, not in /static/ nor
# in /site/data.  Aside from that, the location of this file in the site
# hierarchy doesn't really matter -- the only purpose is to touch a file
# *somewhere*, and the contents are never read by any site files.
TIMESTAMP_FILE="$SITE_ROOT/content/site/packages-spreadsheet-timestamp.txt"

# Get the previous value, compare it, and refresh the timestamp file if
# there's a difference.  Simply touching the timestamp file will cause Hugo
# to regenerate the site, by virtue of its watching for changes in the
# filesystem, so we don't need to do anything more here.  IMPORTANT: the
# Hugo server must be running with --ignoreCache or else it will never
# re-read the spreadsheet data unless the server is restarted completely.
currentvalue=$(curl --silent $TIMESTAMP_URL)
if [[ -f $TIMESTAMP_FILE ]]; then
    lastvalue=$(<$TIMESTAMP_FILE)
    if [[ $lastvalue == $currentvalue ]]; then
        exit 0
    fi
fi

# If we get here, we rewrite the timestamp file with a new value.
echo $currentvalue > $TIMESTAMP_FILE
